# Permalinks
permalink:           pretty

# Setup
title:               scatterings from the Purple Crow Lidar
#tagline:             from the Purple Crow Lidar
url:                 http://purplecrowlidar.ca/blog
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Bob Sica
  url:               https://twitter.com/purplecrowlidar
#  email:             markdotto@gmail.com

# Custom vars
version:             2.0.0
github:
repo:                https://github.com/bobsica/bobsica.github.io/pclblog

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jemoji

